export const baseUrl = process.env.NEXT_PUBLIC_APP_HOST;
export const apiHost = process.env.NEXT_PUBLIC_API_HOST;
export const fetchClientUrl = `${apiHost}/api/whitelabels/`
export const userProfileUrl = `${apiHost}/api/accounts/`
export const userProfileInfoUrl = `${apiHost}/api/accounts/profile/`
export const userRegisterUrl = `${apiHost}/api/accounts/register/`
export const userRetrieveDestroyUrl = `${apiHost}/api/accounts/users/`
export const userLoginAsUrl = `${apiHost}/api/accounts/loginas/`
export const userLoginUrl = `${apiHost}/api/accounts/token/`
export const userLinkedinAccountConnectUrl = `${apiHost}/api/accounts/connect/`
export const userLinkedinAccountDisconnectUrl = `${apiHost}/api/accounts/disconnect/`
export const campaignListCreateUrl = `${apiHost}/api/campaigns/`
export const linkedinAccountsListUrl = `${apiHost}/api/accounts/linkedin-accounts/`
export const campaignLinkedinAccountsCreateUrl = `${apiHost}/api/campaign-linkedin-accounts/`
export const campaignSequenceListCreateUrl = `${apiHost}/api/campaign-sequences/`
export const prospectsListUrl = `${apiHost}/api/prospects/`
export const roomsListUrl = `${apiHost}/api/rooms/`
export const roomReadedUrl = `${apiHost}/api/room-readed/`
export const messagesListUrl = `${apiHost}/api/messages/`
export const triggerCampaignUrl = `${apiHost}/api/trigger/`
export const searchParamterListCreateUrl = `${apiHost}/api/search-parameters/`
export const googleCodeExchangeToAccessTokenUrl = `${apiHost}/api/accounts/connect-google/`
export const countriesUrl = `${apiHost}/api/countries/`
export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID
export const GOOGLE_REDIRECT_URI = `${baseUrl}/google-callback`
export const licenseListUrl = `${apiHost}/api/accounts/license`
export const usersListUrl = `${apiHost}/api/accounts/users/`
export const whitelabelsListUrl = `${apiHost}/api/whitelabels/`
export const labelsListCreateUrl = `${apiHost}/api/labels/`
export const assignLabelViewUrl = `${apiHost}/api/assign-label/`
export const assignsLabelViewUrl = `${apiHost}/api/assign-labels/`
export const generateSSLListUrl = `${apiHost}/api/generate-ssl/`
export const importBulkLinkedinAccounts = `${apiHost}/api/accounts/import-bulk-linkedin-accounts/`
export const linkedinAccountsExampleImportUrl = `https://newson.ytechlabs.co/api/media/import-example.csv`
// export const linkedinAccountsExampleImportUrl = `${apiHost}/api/media/import-example.csv`
export const googleOAuthUrl = () => {
    const googleAuthUrl = 'https://accounts.google.com/o/oauth2/v2/auth';

    const scope = [
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile',
        'https://www.googleapis.com/auth/gmail.modify',
    ].join(' ');

    const params = {
        response_type: 'code',
        client_id: GOOGLE_CLIENT_ID,
        redirect_uri: GOOGLE_REDIRECT_URI,
        scope,
        access_type: 'offline',
        prompt: 'consent'
    };

    const urlParams = new URLSearchParams(params).toString();

    window.location = `${googleAuthUrl}?${urlParams}`;
}

export const countriesList = [
    ['US', 'United States'],
    ['AF', 'Afghanistan'],
    ['AL', 'Albania'],
    ['DZ', 'Algeria'],
    ['AS', 'American Samoa'],
    ['AD', 'Andorra'],
    ['AO', 'Angola'],
    ['AI', 'Anguilla'],
    ['AQ', 'Antarctica'],
    ['AG', 'Antigua And Barbuda'],
    ['AR', 'Argentina'],
    ['AM', 'Armenia'],
    ['AW', 'Aruba'],
    ['AU', 'Australia'],
    ['AT', 'Austria'],
    ['AZ', 'Azerbaijan'],
    ['BS', 'Bahamas'],
    ['BH', 'Bahrain'],
    ['BD', 'Bangladesh'],
    ['BB', 'Barbados'],
    ['BY', 'Belarus'],
    ['BE', 'Belgium'],
    ['BZ', 'Belize'],
    ['BJ', 'Benin'],
    ['BM', 'Bermuda'],
    ['BT', 'Bhutan'],
    ['BO', 'Bolivia'],
    ['BA', 'Bosnia And Herzegowina'],
    ['BW', 'Botswana'],
    ['BV', 'Bouvet Island'],
    ['BR', 'Brazil'],
    ['BN', 'Brunei Darussalam'],
    ['BG', 'Bulgaria'],
    ['BF', 'Burkina Faso'],
    ['BI', 'Burundi'],
    ['KH', 'Cambodia'],
    ['CM', 'Cameroon'],
    ['CA', 'Canada'],
    ['CV', 'Cape Verde'],
    ['KY', 'Cayman Islands'],
    ['CF', 'Central African Rep'],
    ['TD', 'Chad'],
    ['CL', 'Chile'],
    ['CN', 'China'],
    ['CX', 'Christmas Island'],
    ['CC', 'Cocos Islands'],
    ['CO', 'Colombia'],
    ['KM', 'Comoros'],
    ['CG', 'Congo'],
    ['CK', 'Cook Islands'],
    ['CR', 'Costa Rica'],
    ['CI', 'Cote D`ivoire'],
    ['HR', 'Croatia'],
    ['CU', 'Cuba'],
    ['CY', 'Cyprus'],
    ['CZ', 'Czech Republic'],
    ['DK', 'Denmark'],
    ['DJ', 'Djibouti'],
    ['DM', 'Dominica'],
    ['DO', 'Dominican Republic'],
    ['TP', 'East Timor'],
    ['EC', 'Ecuador'],
    ['EG', 'Egypt'],
    ['SV', 'El Salvador'],
    ['GQ', 'Equatorial Guinea'],
    ['ER', 'Eritrea'],
    ['EE', 'Estonia'],
    ['ET', 'Ethiopia'],
    ['FK', 'Falkland Islands [Malvinas)'],
    ['FO', 'Faroe Islands'],
    ['FJ', 'Fiji'],
    ['FI', 'Finland'],
    ['FR', 'France'],
    ['GF', 'French Guiana'],
    ['PF', 'French Polynesia'],
    ['TF', 'French S. Territories'],
    ['GA', 'Gabon'],
    ['GM', 'Gambia'],
    ['GE', 'Georgia'],
    ['DE', 'Germany'],
    ['GH', 'Ghana'],
    ['GI', 'Gibraltar'],
    ['GR', 'Greece'],
    ['GL', 'Greenland'],
    ['GD', 'Grenada'],
    ['GP', 'Guadeloupe'],
    ['GU', 'Guam'],
    ['GT', 'Guatemala'],
    ['GN', 'Guinea'],
    ['GW', 'Guinea-bissau'],
    ['GY', 'Guyana'],
    ['HT', 'Haiti'],
    ['HN', 'Honduras'],
    ['HK', 'Hong Kong'],
    ['HU', 'Hungary'],
    ['IS', 'Iceland'],
    ['IN', 'India'],
    ['ID', 'Indonesia'],
    ['IR', 'Iran'],
    ['IQ', 'Iraq'],
    ['IE', 'Ireland'],
    ['IL', 'Israel'],
    ['IT', 'Italy'],
    ['JM', 'Jamaica'],
    ['JP', 'Japan'],
    ['JO', 'Jordan'],
    ['KZ', 'Kazakhstan'],
    ['KE', 'Kenya'],
    ['KI', 'Kiribati'],
    ['KP', 'Korea [North)'],
    ['KR', 'Korea [South)'],
    ['KW', 'Kuwait'],
    ['KG', 'Kyrgyzstan'],
    ['LA', 'Laos'],
    ['LV', 'Latvia'],
    ['LB', 'Lebanon'],
    ['LS', 'Lesotho'],
    ['LR', 'Liberia'],
    ['LY', 'Libya'],
    ['LI', 'Liechtenstein'],
    ['LT', 'Lithuania'],
    ['LU', 'Luxembourg'],
    ['MO', 'Macau'],
    ['MK', 'Macedonia'],
    ['MG', 'Madagascar'],
    ['MW', 'Malawi'],
    ['MY', 'Malaysia'],
    ['MV', 'Maldives'],
    ['ML', 'Mali'],
    ['MT', 'Malta'],
    ['MH', 'Marshall Islands'],
    ['MQ', 'Martinique'],
    ['MR', 'Mauritania'],
    ['MU', 'Mauritius'],
    ['YT', 'Mayotte'],
    ['MX', 'Mexico'],
    ['FM', 'Micronesia'],
    ['MD', 'Moldova'],
    ['MC', 'Monaco'],
    ['MN', 'Mongolia'],
    ['MS', 'Montserrat'],
    ['MA', 'Morocco'],
    ['MZ', 'Mozambique'],
    ['MM', 'Myanmar'],
    ['NA', 'Namibia'],
    ['NR', 'Nauru'],
    ['NP', 'Nepal'],
    ['NL', 'Netherlands'],
    ['AN', 'Netherlands Antilles'],
    ['NC', 'New Caledonia'],
    ['NZ', 'New Zealand'],
    ['NI', 'Nicaragua'],
    ['NE', 'Niger'],
    ['NG', 'Nigeria'],
    ['NU', 'Niue'],
    ['NF', 'Norfolk Island'],
    ['MP', 'Northern Mariana Islands'],
    ['NO', 'Norway'],
    ['OM', 'Oman'],
    ['PK', 'Pakistan'],
    ['PW', 'Palau'],
    ['PA', 'Panama'],
    ['PG', 'Papua New Guinea'],
    ['PY', 'Paraguay'],
    ['PE', 'Peru'],
    ['PH', 'Philippines'],
    ['PN', 'Pitcairn'],
    ['PL', 'Poland'],
    ['PT', 'Portugal'],
    ['PR', 'Puerto Rico'],
    ['QA', 'Qatar'],
    ['RE', 'Reunion'],
    ['RO', 'Romania'],
    ['RU', 'Russian Federation'],
    ['RW', 'Rwanda'],
    ['KN', 'Saint Kitts And Nevis'],
    ['LC', 'Saint Lucia'],
    ['VC', 'St Vincent/Grenadines'],
    ['WS', 'Samoa'],
    ['SM', 'San Marino'],
    ['ST', 'Sao Tome'],
    ['SA', 'Saudi Arabia'],
    ['SN', 'Senegal'],
    ['SC', 'Seychelles'],
    ['SL', 'Sierra Leone'],
    ['SG', 'Singapore'],
    ['SK', 'Slovakia'],
    ['SI', 'Slovenia'],
    ['SB', 'Solomon Islands'],
    ['SO', 'Somalia'],
    ['ZA', 'South Africa'],
    ['ES', 'Spain'],
    ['LK', 'Sri Lanka'],
    ['SH', 'St. Helena'],
    ['PM', 'St.Pierre'],
    ['SD', 'Sudan'],
    ['SR', 'Suriname'],
    ['SZ', 'Swaziland'],
    ['SE', 'Sweden'],
    ['CH', 'Switzerland'],
    ['SY', 'Syrian Arab Republic'],
    ['TW', 'Taiwan'],
    ['TJ', 'Tajikistan'],
    ['TZ', 'Tanzania'],
    ['TH', 'Thailand'],
    ['TG', 'Togo'],
    ['TK', 'Tokelau'],
    ['TO', 'Tonga'],
    ['TT', 'Trinidad And Tobago'],
    ['TN', 'Tunisia'],
    ['TR', 'Turkey'],
    ['TM', 'Turkmenistan'],
    ['TV', 'Tuvalu'],
    ['UG', 'Uganda'],
    ['UA', 'Ukraine'],
    ['AE', 'United Arab Emirates'],
    ['UK', 'United Kingdom'],
    ['UY', 'Uruguay'],
    ['UZ', 'Uzbekistan'],
    ['VU', 'Vanuatu'],
    ['VA', 'Vatican City State'],
    ['VE', 'Venezuela'],
    ['VN', 'Viet Nam'],
    ['VG', 'Virgin Islands [British)'],
    ['VI', 'Virgin Islands [U.S.)'],
    ['EH', 'Western Sahara'],
    ['YE', 'Yemen'],
    ['YU', 'Yugoslavia'],
    ['ZR', 'Zaire'],
    ['ZM', 'Zambia'],
    ['ZW', 'Zimbabwe']
]